name: Demarc.us
favicon: null
layout_spectrum: 0.23157983948476613
typography_spectrum: 0.5719769347924739
title: Demarc.us
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7a8c8c'
    - '#512427'
    - '#55605c'
    - '#0a0000'
  brandStrength: 1
  lightness: 0.625
  saturation: 0
  rhythmicContrast: 1
purpose: []
